### ISSUE TITLE
Can't connect to the IRC relay

### ISSUE THREAD

**Issue by acagastya** [mhoran/weechatRN#32]
Hi, I am running a IRC relay on port 5555 (SSL is enabled).  I tried logging in by entering `example.con:5555` and entering the password.  But all I get in the console is:

```
Sending data: (version) info version
Sending data: (hotlist) hdata hotlist:gui_hotlist(*)
Sending data: (buffers) hdata buffer:gui_buffers(*) local_variables,notify,number,full_name,short_name,title,hidden,type
Sending data: sync
Sending data: (input) input core.weechat /weechatrn ExponentPushToken[SOMETOKEN]
```

How can I make this work?

**Comment by acagastya** [comment]
Looks like it works for weechat relay, but not IRC relay -- is it supposed to be like that?

**Comment by mhoran** [comment]
Hey! Thanks for checking out weechatRN. weechatRN only supports connecting via the relay protocol, not the IRC protocol. The relay protocol is much richer and allows weechat itself to act as a server for weechatRN. This means weechatRN can pull the backlog and other things from weechat instead of having to maintain its own state. Hope that helps!

**Comment by acagastya** [comment]
Thanks for clarifying, @mhoran.  I had both IRC relay and weechat relay running, and so I was able to use it.  Could you please update the README to mention that?
