### ISSUE TITLE
Can't see list of users in the channel

### ISSUE THREAD

**Issue by acagastya** [mhoran/weechatRN#33]
Right now, on iOS and on Andriod, no swipe gestures show the list of nicks currently on the channel.  Could you please add that?

**Comment by mhoran** [comment]
Thanks for the request! Yes, I plan to add this functionality. In the meantime you can use the `/names` command to list users in IRC buffers.

Also, on Android I'd recommend the excellent [weechat-android](https://github.com/ubergeek42/weechat-android) project, which I also help maintain. My primary focus for weechatRN is iOS.

**Comment by acagastya** [comment]
Oh, that is wonderful to know you would be adding it!  In that case, should I rename the issue as "[FEAT req] display nicks in a channel"?  Should I leave the issue open?

**Comment by mhoran** [comment]
It's fine as is -- I can edit if needed. I'm the only one working on this so the open issues are basically my backlog. If needed I will rename.

If you'd like I can add you to TestFlight so that any updates get pushed and you don't have to use Expo directly. Shoot me an email if you'd like (see my GitHub profile) and I'll send over an invite.

**Comment by acagastya** [comment]
Just did!

**Comment by acagastya** [comment]
Might I add, the colour of nicks which are online be white, and those who are `/away` be in grey.
