### ISSUE TITLE
Does this project work with unsecured relays? How to get into TestFlight?

### ISSUE THREAD

**Issue by hrvstr** [mhoran/weechatRN#36]
Hi, I would like to test this project without building it myself. How can I get into Testflight?

Also I would like to connect to a relay on my LAN without opening ports to the internet and getting a domain etc. Is this possible?

Thanks!

**Comment by mhoran** [comment]
Hey! Thanks for your interest in the project. I haven't submitted the app for TestFlight reviews, so I can't invite anyone else at this time. It'll take a bit of work to get things set up for review and I'm not even sure if it would be accepted since it's not quite an iOS native experience, but I plan to look into it.

Unfortunately Apple forced the Expo team to make things a bit more difficult for others to launch projects, so the only way to test things as they are today is by setting up Expo locally. But once you do that it should be pretty easy to open the app on your device. I wish I had a better answer. I'll have to look into getting the TestFlight build reviewed.

In terms of connecting without opening ports, yes, that's totally possible. Of course, it wouldn't work from the Internet, but so long as you can reach the host from your device on the LAN, that's fine.

**Comment by LovingMelody** [comment]
Maybe opting for AltStore might help if you cannot get test flgiht

**Comment by mhoran** [comment]
FYI: WeechatRN has been approved for public testing. You can join the beta test here: https://testflight.apple.com/join/0jFsQpot.
